name: Cleanup SNAPSHOTs

on:
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old snapshot versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: de.magicthings.spring-reactive-mongo-filter
          package-type: maven
          min-versions-to-keep: 5
          ignore-versions: '^(?!.*SNAPSHOT).*$'